@startuml

package Integrations <<Frame>> {
    class Webhook {
        id: String
        name: String
        secret: String
        channel: String
        actor: Actor
    }
}

package Channels <<Frame>> {
    enum ChannelType {
       PUBLIC
       PRIVATE
    }

    class Channel {
        id: String
        type: ChannelType
        owner: Actor
        created: Date
    }
    Webhook "1" *-- "n" Channel : belongs to

    class Subscription {
        actor: Actor
        channel: Channel
        viewedUntil: Date
        desktopNotification: NotificationSetting
        mobileNotification: NotificationSetting
        emailNotification: NotificationSetting
    }
    Subscription "n" *-- "1" Channel
}

package Authentication <<Frame>> {
    enum ActorType {
        Person
        Server
        Bot
        Group
    }

    enum ActorRole {
        ADMIN
        USER
    }

    class Actor {
        id: String
        type: ActorType
        username: String
        role: ActorRole
        name: String
        email: String
        password: String
    }

    Subscription "n" *-- "1" Actor
    Webhook "1" *-- "n" Actor : post for

'    class Group {
'        owner: Actor
'        members: Actor[]
'        channels: Channel[]
'    }
'    Actor <|-- Group
'    Group "0..1" *-- "n" Channel : belongs to
'    Group "0..1" *-- "n" Actor : is member of

}

package Authorization <<Frame>> {

    class AclRole {
        id: String
        weight: Integer
        parent: AclRole
    }

    class AclEntry {
        topic: String
        actions: String
        memberActions: String
        ownerActions: String
        roleTarget: Role
    }

    note left of AclEntry
     c=create Object
     r=read Object
     u=update Object
     d=delete Object
     x=execute RPC
     e=enter Channel
     l=leave Channel
     p=publish in Channel
    end note

    AclEntry "n" *-- "1" AclRole : associated to
}



@enduml