apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: socketcluster
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: socketcluster
    spec:
      containers:
      - name: socketcluster
        image: peuter/deernation-backend:latest
        ports:
        - containerPort: 6878
        env:
        - name: SCC_STATE_SERVER_HOST
          value: scc-state
        - name: SOCKETCLUSTER_WORKERS
          value: "1"
        - name: SOCKETCLUSTER_BROKERS
          value: "1"
        - name: SCC_INSTANCE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ENV
          value: prod
        livenessProbe:
          httpGet:
            path: /health-check
            port: 6878
          initialDelaySeconds: 30
          timeoutSeconds: 5
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - socketcluster
            topologyKey: "kubernetes.io/hostname"